### ISSUE TITLE
Fails to build from source

### ISSUE THREAD

**Issue by ElPistoler0** [caddyserver/ntlm-transport#4] opened 2022-07-25 14:33 UTC
Hi,

When trying to build Caddy from source using xCaddy, I get this error:

2022/07/25 09:24:05 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/ntlm-transport github.com/caddyserver/caddy/v2 
go: downloading github.com/caddyserver/ntlm-transport v0.1.2
go get: github.com/caddyserver/ntlm-transport@upgrade (v0.1.2) requires github.com/caddyserver/caddy/v2@v2.5.3-0.20220713145230-c2bbe42fc355, not github.com/caddyserver/caddy/v2@upgrade (v2.5.2)
2022/07/25 09:24:07 [FATAL] exit status 1

Any idea how to fix?

Thanks!

Francisco

**Comment by ElPistoler0** [comment] 2022-07-25 16:09
BTW, set this var but still getting no love

2022/07/25 11:08:01 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/ntlm-transport github.com/caddyserver/caddy/v2 
go: github.com/caddyserver/ntlm-transport@upgrade (v0.1.2) requires github.com/caddyserver/caddy/v2@v2.5.3-0.20220713145230-c2bbe42fc355, not github.com/caddyserver/caddy/v2@upgrade (v2.5.2)
2022/07/25 11:08:02 [FATAL] exit status 1
root@DP1:~# echo $CADDY_VERSION                                   
c2bbe42fc3553f6a5685cdb45453c0950fa614b2

**Comment by mholt** [comment] 2022-07-25 16:23
Duplicate of https://github.com/caddyserver/ntlm-transport/issues/3

**Closed as completed by mholt** 2022-07-25 16:23 UTC
